### PR TITLE
Add support for Guzzle 6.x

### PR DESCRIPTION
**Pull request by danmichaelo**
Tested with Guzzle 6.0.1. Should still work with Guzzle 5.x

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Our plan was to drop guzzle 5 and only support guzzle 6, but this has to be done in every single adapter.

**Comment by danmichaelo** [comment]
Sure makes it easier to maintain. Feel free to close this PR then. I'll use my own fork until it's ready.

**Comment by jbrooksuk** [comment]
@danmichaelo or feel free to apply this to all other adapters ;)

**Comment by danmichaelo** [comment]
Ehm, please decide if you want to support Guzzle 5 or not first. If you decide to keep Guzzle 5 support on all adapters, I guess it would be better to add some logic to a central place like `HttpGatewayTrait`, right? Which should be discussed at the central repo. Feel free to ping me if you decide to keep Guzzle 5, I can surely join in. I don't need Guzzle 5 support myself though, it just bothers me that there's so little backwards compability with composer packages in general, so I try to add backwards compability whenever I suggest an update to something. But in this case I'm not really sure if it's worth the effort.

**Comment by GrahamCampbell** [comment]
> Ehm, please decide if you want to support Guzzle 5 or not first.

We have already decided. As I said, we are supporting guzzle 5 ONLY for now, but at some point we still switch to support guzzle 6 ONLY.

**Comment by danmichaelo** [comment]
Ok, then it's no need to keep this open.

**Pull request closed without merging**
